dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=zoom-transcript-edit
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-pc-windows-gnu
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  provider: cargo
  token:
    secure: ZkYFbqY9x3OmMMPy5xMe4/5f+1PjCqrm7YlBQ41BVECJ3SygBHulyEr82fXlC/uB3aEeO9aDkDexMcmw+7bwSjakfPxsSaJbYom2/gyt6NRiXYv+kQvOgGVaFfjB4MtFLM9dPcR4Ao1aTHNBfblivx4PzGM45UNWlJcwKM0JXyVixulagNxYMmVQs/xvKnUAu5YRag6P7W2kM1hbIxvoZ3M0fG32cmjhoFw1IdEgPtxJkBNbNMFxBZANOAJZxEnGpIoZZdxBtcTk60Ia5DAtte/fCY37cdw6+yZHPtfga0fgbeohhukOPducc/MepMXDbAN2doo+f9wh09yb1l1WlocUZcBp1Yy87POblzkck5BOLzdm4JauksDJEXdb19XxlRFtEWU6hgshkppv1Lq6kRkBrpbP8ODkrYMyYVBDOS6Pxjzoz+B9sCRnaMsLPnWTJI9iwWUPJqnoYnqw1mvsqFA3w3f74UW+fHdp0KREevijeAyWKZxlnbFRujjnuvvj1BBsuU/reqR0gysB9WdsaZXTgwzfRxYUzaHysz+QmfKF9pKYDNuiH6Im/7nqVz6Ra9I1mLMBoeARqzH5Ao5RiI9s2ldM7CP10nU//4Y0B9GswH1rducTJxGsVulbfBB0KrJBmJi7BBIE8pG3FxJv1sXAdgSAtquNPYG4N2p9Azg=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - trunk
notifications:
  email:
    on_success: never
