[package]
name = "zoom-transcript-edit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
contracts = "^0.6.1"
chrono = "^0.4.19"

[dev-dependencies]
